### ISSUE TITLE
Discussion: why change the structure?

### ISSUE THREAD

**Issue by matiboy** [pfernandom/aws-api-client#4]
Hi @pfernandom 

Thanks for this package; it's really surprising that AWS API Gateway has this **awesome** feature of auto creating an SDK, but that they couldn't be bothered making it usable in modern dev environments. So thanks for taking the time to make this into an npm package.

Referring to #3 and to the README (change things in apigClient.js), I was wondering whether it would make sense instead to keep the same structure as what AWS provides and only having the import of `apiGateway`. The rest of the code in apigClient.js wouldn't need to be changed.

What are your thoughts?

Thanks

Mat

**Comment by matiboy** [comment]
PS: that would also allow to use webpack's `imports-loader` and `exports-loader` so no work would even be needed when one downloads a new version of their SDK

**Comment by pfernandom** [comment]
Hello @matiboy 

Sorry for getting back to you so late. I missed the notifications about your comment and changes. 

I completely agree with you. Being able to keep apigClient.js without changes would allow people to be up and running a lot faster.

I just merged your changes. Thanks for the contribution.

**Comment by matiboy** [comment]
@pfernandom No problem and thank you for merging 👍
